# Generated by Django 4.2.3 on 2023-07-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_spell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('spells', models.ManyToManyField(to='main_app.spell')),
            ],
        ),
    ]
