# Generated by Django 4.2.3 on 2023-07-12 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_weapontype_weapon_character_weapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='arcStat',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
