# Generated by Django 4.2.3 on 2023-07-12 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_character_arcstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dexStat',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='character',
            name='endStat',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='character',
            name='faiStat',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='character',
            name='intStat',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='character',
            name='mindStat',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='character',
            name='strStat',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='character',
            name='vigStat',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
