# Generated by Django 4.2.3 on 2023-07-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_chestplate_gloves_helmet_leggings_talisman_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talisman',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
