# Generated by Django 4.2.3 on 2023-07-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_talisman_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chestplate',
            name='img',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='chestplate',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gloves',
            name='img',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='gloves',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='img',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='leggings',
            name='img',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='leggings',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='talisman',
            name='img',
            field=models.CharField(default='', max_length=500),
        ),
    ]
