# Generated by Django 4.2.3 on 2023-07-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_chestplate_img_alter_chestplate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='chestplate',
            field=models.ManyToManyField(to='main_app.chestplate'),
        ),
        migrations.AddField(
            model_name='character',
            name='gloves',
            field=models.ManyToManyField(to='main_app.gloves'),
        ),
        migrations.AddField(
            model_name='character',
            name='helmet',
            field=models.ManyToManyField(to='main_app.helmet'),
        ),
        migrations.AddField(
            model_name='character',
            name='leggings',
            field=models.ManyToManyField(to='main_app.leggings'),
        ),
    ]
